const productCat = [
    {
    id:1,
    imageUrl:"src/Images/Api-images/HP.png",
    nameOfProduct:"Lenovo Thinkpad",
    category:"  Computer and Accessories",
    price:927800,
    description:" E14, Intel Core I5-1135g7, 8gb Ram, 256gb Ssd Black (20ta000yue)",
    discountPercentage: "10"
    },
    
    {id:2,
    imageUrl:"src/Images/Api-images/HP.png",
    nameOfProduct:"HP Elitebook",
    category:"Computer and Accessories",
    price:927800,
    description:"Hp 240 G9 I7-1255u 14 8gb 256GB Pc - (777m2es)",
    discountPercentage: "15"},
    
    {id:3,
    imageUrl:"src/Images/Api-images/Zinox.png",
    nameOfProduct:"Zinox Phoenix",
    category:"Computer and Accessories",
    price:660000,
    description:" 14” Fhd Ips, Intel Core i3-10110u, 8g -256gb Ssd - Win 11",
    discountPercentage: "20"},
    
    {id:4,
    imageUrl:"src/Images/Api-images/Vga-adapter.png",
    nameOfProduct:"Vga Adapter",
    category:"Computer and Accessories",
    price:3000,
    description:"Display To Vga Adapter",
    discountPercentage: "10"},
                
    {id:5,
    imageUrl:"src/Images/Api-images/LaptopStand.png",
    nameOfProduct:"A&S Laptop Stand",
    category:"Computer and Accessories",
    price:7500,
    description:"A&S Laptop Stand",
    discountPercentage: "15"},
                    
    {id:6,
    imageUrl:"src/Images/Api-images/Ups.png",
    nameOfProduct:"UPS",
    category:"Computer and Accessories",
    price:32900,
    description:"Mini Ups For Router Linkcomn Kp2 Poe 10000mAh",
    discountPercentage: "20"},
                        
    {id:7,
    imageUrl:"src/Images/Api-images/Wireless mouse.png",
    nameOfProduct:"Wireless mouse",
    category:"Computer and Accessories",
    price:4500,   
    description:"HP Ultra-slim USB 2.4ghz Wireless Mouse - Black",
    discountPercentage: "10"},
                            
    {id:8,
    imageUrl:"src/Images/Api-images/Flash drive.png",
    nameOfProduct:"Flash drive",
    category:"Computer and Accessories",
    price:13000,
    description:"SanDisk Cruzer Glide 3.0 USB Flash Drive-16GB",
    discountPercentage: "10"},
    
    {id:9,
    imageUrl:"src/Images/Api-images/Iphone15.png",
    nameOfProduct:"Apple iPhone 15 Pro",
    category:"Phone and Tablet",
    price:1796500,
    description:" 128GB White Titanium",
    discountPercentage: "10"},
                                    
    {id:10,
    imageUrl:"src/Images/Api-images/Samsung.png",
    nameOfProduct:"Samsung Galaxy",
    category:"Phone and Tablet",
    price:310000,
    description:"Samsung Galaxy A15 Lte -6.6''-256gb Rom -8gb Ram -5000mah- Blue",
    discountPercentage: "15"},

        {id:11,
        imageUrl:"src/Images/Api-images/Infinix.png",
        nameOfProduct:"Infinix",
        category:"Phone and Tablet",
        price:312000,
        description:"Infinix Note 30 5G X6711- 6.78 4gb+4gb Ram -128gb Rom -dual Sim -108mp - Fingerprint - 5000mah- Gold",
        discountPercentage: "20"
        },

        {id:12,
        imageUrl:"src/Images/Api-images/Techno.png",
        nameOfProduct:"Techno",
        category:"Phone and Tablet",
        price:250000,
        description:"Tecno SPARK 20 PRO KJ6 -6.78- 256GB ROM+8GBRAM- 108mp+32mp- 5000 Mah- BLACK",
        discountPercentage: "10"},

        {id:13,
        imageUrl:"src/Images/Api-images/Huawei.png",
        nameOfProduct:"Huawei",
        category:"Phone and Tablet",
        price:1650000,
        description:"Huawei Pura 70 Ultra Dual Sim - 16GB RAM - 512GB ROM- 5G - 5200mAh -Brown",
        discountPercentage: "15"},

        {id:14,
        imageUrl:"src/Images/Api-images/Oppo.png",
        nameOfProduct:"Oppo",
        category:"Phone and Tablet",
        price:190000,
        description:"Oppo A38 - 6.56 - 128gb Rom - 6gb Ram - 4G LTE - Dual Sim - 50mp - Fingerprint - 5000mah - Black",
        discountPercentage: "20"},

        {id:15,
        imageUrl:"src/Images/Api-images/ZTE.png",
        nameOfProduct:"ZTE",
        category:"Phone and Tablet",
        price:93000,
        description:"ZTE A35 - blk - 4GB ROM - 64GB RAM - 5000mAh - Black",
        discountPercentage: "12"},

        {id:16,
        imageUrl:"src/Images/Api-images/Itel.png",
        nameOfProduct:"Itel",
        category:"Phone and Tablet",
        price:92800,
        description:"Itel A50 6.5 - 2gb Ram - 64gb Rom - 5000mah- Cyan Blue",
        discountPercentage: "15"},

        {id:17,
        imageUrl:"src/Images/Api-images/Nexus tv.png",
        nameOfProduct:"Nexus tv",
        category:"Electronics",
        price:116600,
        description:"Nexus 32 HD Led-nx-tv620b (sa) + 1 year warranty",
        discountPercentage: "10"},

        {id:18,
        imageUrl:"src/Images/Api-images/Samsung tv.png",
        nameOfProduct:"Samsung tv",
        category:"Electronics",
        price:511800,
        description:"Samsung Ua43t5300 aux  43” Full Hd Smart Tv",
        discountPercentage: "15"},

        {id:19,
        imageUrl:"src/Images/Api-images/Hisense woofer.png",
        nameOfProduct:"Hisense Woofer",
        category:"Electronics",
        price:139000,
        description:"Hisense Aud 350ha Mini Hifi, Hdmi, Bluetooth, Usb, 100 Watts, 5.2woofer",
        discountPercentage: "20"},

        {id:20,
        imageUrl:"src/Images/Api-images/Camera.png",
        nameOfProduct:"Camera",
        category:"Electronics",
        price:840000,

        description:"Insta Natural Ace Pro - Waterproof Action Camera Co-engineered With Leica, Flagship 1/1.3 Sens",
        discountPercentage: "10"},
        {
        id:21,
        imageUrl:"src/Images/Api-images/Bluetooth.png",
        nameOfProduct:"Bluetooth",
        category:"Electronics",
        price:65000,
        description:"Zealot S67 Portable Wireless Bluetooth Speaker - 60w",
        discountPercentage: "15"
        },

        {id:22,
        imageUrl:"src/Images/Api-images/Mic.png",
        nameOfProduct:"Wireless Mic",
        category:"Electronics",
        price:20000,
        description:"K9 Wireless Lapel Microphone",
        discountPercentage: "5"},
        
        {id:23,
        imageUrl:"src/Images/Api-images/Headphone.png",
        nameOfProduct:"Headphone",
        category:"Electronics",
        price:89000,
        description:"Behringer Hpx6000 Professional Dj Headphones",
        discountPercentage: "15"},
        
        {id:24,
        imageUrl:"src/Images/Api-images/Mixer.png",
        nameOfProduct:"Mixer",
        category:"Electronics",
        price:60000,
        description:"Professional Mixer Live Sound Card And Effects With Dj Mixer",
        discountPercentage: "10"},

        {id:25,
        imageUrl:"src/Images/Api-images/Sneakers.png",
        nameOfProduct:"Sneakers",
        category:"Konga Fashion",
        price:7000,
        description:"Men's Sneakers",
        discountPercentage: "20"},
        {id:26,
        imageUrl:"src/Images/Api-images/Wristwatch.png",
        nameOfProduct:"Wrist watch",
        category:"Konga Fashion",
        price:23500,

        description:"Chronograph Gold wristwatch",
        discountPercentage: "20"},
        {id:27,
        imageUrl:"src/Images/Api-images/Moccasine.png",
        nameOfProduct:"Moccasine",
        category:"Konga Fashion",
        price:23000,
        description:"Sebago Dockside Moccasine Boat Shoes",
        discountPercentage: "15"},
        {id:28,
        imageUrl:"src/Images/Api-images/Necklace.png",
        nameOfProduct:"Necklace",
        category:"Konga Fashion",
        price:1800,
        description:"Mom Necklace- Gold",
        discountPercentage: "20"},
        
        {id:29,
        imageUrl:"src/Images/Api-images/Purse.png",
        nameOfProduct:"Purse",
        category:"Konga Fashion",
        price:27000,
        description:"Ladies Clutch Purse - Gold",
        discountPercentage: "15"},
        
        {id:30,
        imageUrl:"src/Images/Api-images/Jacket & Joggers.png",
        nameOfProduct:"Jacket",
        category:"Konga Fashion",price:27000,
        description:"Varsity Jacket With Joggers - White/black",
        discountPercentage: "20"},
        {
        id:31,
        imageUrl:"src/Images/Api-images/Glasses.png",
        nameOfProduct:"Glass",
        category:"Konga Fashion",
        price:18200,
        description:"Unisex Square Eye Glasses - Black",
        discountPercentage: "20"
        },

        {id:32,
        imageUrl:"src/Images/Api-images/Earring.png",
        nameOfProduct:"Earring",
        category:"Konga Fashion",
        price:13800,
        description:"Fashion Jewelry Tassel Stud Ball Drop Earring Bundle",
        discountPercentage: "15"} 
        
]
        export default productCat;

